### ISSUE TITLE
summary(model, standardized=TRUE) error

### ISSUE THREAD

**Issue by david-vas** [simsem/semTools#50] opened 2018-12-05 12:05 UTC
When I try to obtain standardized estimates for a model (based on 5 imputed datasets using the mice package) using the summary(object, standardized=TRUE) formula, I get an error stating:

 _'Error in lav_standardize_all(object, est = est, GLIST = GLIST, partable = partable,  : 
  no slot of name "SampleStats" for this object of class "lavaan.mi"'_

However, when I use only summary(object), I do obtain unstandardized estimates without problems. 

When I check the object, there is a SampleStatsList, so I think the object is not missing.

It is a sem model with several exogenous variables (3 items, 7 latent factors) that predict two latent factors. The model converged on all 5 imputed datasets.

Could it be a bug?

**Comment by TDJorgensen** [comment] 2018-12-05 12:49
Not sure what is happening in your case, but the help-page example works fine when it requests the standardized solution.  The `@SampleStats` slot from lavaan objects is not the same as the `@SampleStatsList` from lavaanList objects (lavaan.mi inherits from the latter), but I pass the information manually so `@SampleStats` should not be needed.  It might have been a bug that is already fixed.  Which versions do you have installed?

```
sessionInfo()
```

I am using semTools 0.5-1.906 (the latest development version) and lavaan 0.6-3 (the version on CRAN).  You can install the development version of semTools using

```
devtools::install_github("simsem/semTools/semTools")
```

**Comment by david-vas** [comment] 2018-12-05 13:37
I tried installing the latest version. sessionInfo() says I'm using semTools_0.5-1.907 lavaan_0.6-4.1348. 

I've tried changing the model and removing predictors that are only represented by one item (not a latent factor). For that solution, summary(object, standardized=TRUE) provides me with standardized estimates. So I guess that there could be some issue with pooling the final, more complex solution?

**Comment by TDJorgensen** [comment] 2018-12-05 14:17
Hmmm, sounds like this has something to do with looking for sample statistics of exogenous variables when those values are not treated as model parameters.  In your full model, try setting `fixed.x=FALSE` so that the exogenous observed predictors are treated as random variables.  If that works, then I know what to look for to fix the problem when `fixed.x=TRUE`.

**Comment by david-vas** [comment] 2018-12-05 15:52
I tried using the fixed.x=FALSE (and also conditional.X=FALSE as the analysis would not proceed stating "lavaan ERROR: fixed.x = FALSE is not supported when conditional.x = TRUE." otherwise). I obtained the results and summary(object, standardized=TRUE) provided me with standardized estimates. The model did not converge for one of the 5 datasets, tho, so it was pooled across 4 of them. It does converge for all 5 datasets when those variables are not treated as part of the model. So I think the problem is where you suggested it could be?

**Comment by TDJorgensen** [comment] 2018-12-05 16:06
I can't speak as to why the model as trouble converging when treating the exogenous variables as random, but it would be wise to use a larger number of imputations.  Yes, the fact that it succeeds in providing standardized output when they are not fixed is enough information for me to eventually track down the problem.  I only recently allowed for `fixed.x = TRUE` and `conditional.x = TRUE` in `runMI()`, so I need to put in some more work on allowing for those options.  FYI, the `fitted()` and `resid()` methods will also currently fail if `conditional.x = TRUE`.  I am hoping to have more time for programming (other than quick bug fixes) in February or March, but I will post an update here when I resolve the issue.

**Comment by timcadman** [comment] 2019-05-22 11:47
Hi there,

I'm running into the same problem - were you able to make any progress with this?

Best wishes,

Tim

**Comment by TDJorgensen** [comment] 2019-05-22 13:36
Not yet, my priorities kept getting pulled toward other aspects of the package that needed to coincide with a paper under review.  I anticipate having time to finish addressing `lavaan.mi` functionality for multilevel data and for `fixed.x` & `conditional.x` situations this summer.  I will post here when the issue is resolved.  Until then, you just need to set them both `FALSE` in order to obtain `standardized` estimates, `fitted()` values, or `residuals()`.  Everything else should work fine.

**Comment by timcadman** [comment] 2019-05-22 13:41
Great thank you - will do

**Comment by timcadman** [comment] 2019-05-22 15:35
Hmm when I set fixed.x and conditional.x to FALSE the model will no longer converge. May have to wait for the update!

cheers

**Comment by TDJorgensen** [comment] 2019-05-22 16:06
It won't converge on any data sets?  Have you tried fitting it to the first imputation to verify that?  I recall a strange anomaly where convergence seemed to fail even though it succeeded when fitting the model to each data set...

**Comment by timcadman** [comment] 2019-05-23 09:15
Thanks for getting back to me. Nope same result if I try it just on the first imputation - it times out at 10,000 iterations. If I set fixed.x and conditional.x back to TRUE it converges fine (199 iterations). If it's helpful I can post the model I'm trying to fit.

**Comment by TDJorgensen** [comment] 2019-05-23 10:17
My only guess would be the model is too large for the sample size to support.  How many fixed-exogenous covariates do you have, and endogenous, and sample size?  Are there many thresholds (for ordered variables)?

**Comment by timcadman** [comment] 2019-05-23 11:33
Quite possible. Sample size is ~8,000. Only 3 exogenous covariates but model includes 6 factors all with ordinal indicators (4 levels) so lots of parameters to estimate (model syntax below).

Would an alternative be to:

(i) run the model separately on each imputed dataset (using fixed.x = TRUE and conditional.x = TRUE), 
(ii) use parameterEstimates to extract standardised coefficients for each imputation,,
(iii) use an external function (e.g. "mi.meld" from Amelia) to pool the estimates?

many thanks again

model <- '

## Measurement model

factor_a_t1 =~ kw6504 + kw6506 + kw6511 + kw6517 + kw6521 + 
            kw6501 + kw6509 + kw6514 + kw6520 + kw6524

factor_b_t1 =~ ccj105 + ccj160 + ccj152 + ccj123 + ccj144 + 
              ccj130 + ccj145

factor_c_t1 =~ ccj100 + ccj142 + ccj132

factor_a_t2 =~ ta7006 + ta7004 + ta7011 + ta7017 + ta7021 + 
            ta7020 + ta7024 + ta7001 + ta7009 + ta7014

factor_b_t2 =~ ccr116 + ccr102 + ccr118 + ccr117 + ccr109 + 
               ccr115 + ccr110

factor_c_t2 =~ ccr100 + ccr113 + ccr111


## Covariances between factors
factor_a_t1 ~~ factor_b_t1
factor_b_t1 ~~ factor_c_t1
factor_a_t1 ~~ factor_c_t1

factor_a_t2 ~~ factor_b_t2
factor_b_t2 ~~ factor_c_t2
factor_a_t2 ~~ factor_c_t2

## Additional correlations between same items at different time points
kw6504 ~~ ta7004
kw6506 ~~ ta7006
kw6511 ~~ ta7011
kw6517 ~~ ta7017
kw6521 ~~ ta7021
kw6501 ~~ ta7001
kw6509 ~~ ta7009
kw6514 ~~ ta7014
kw6520 ~~ ta7020
kw6524 ~~ ta7024
ccr116 ~~ ccj145
ccr102 ~~ ccj105
ccr118 ~~ ccj160
ccr117 ~~ ccj152
ccr109 ~~ ccj123
ccr115 ~~ ccj144
ccr110 ~~ ccj130
ccr100 ~~ ccj100
ccr113 ~~ ccj142
ccr111 ~~ ccj132

## Regressions

factor_a_t1 ~ covariate_1 + covariate_2 + covariate_3
factor_b_t1 ~ covariate_1 + covariate_2 + covariate_3
factor_c_t1 ~ covariate_1 + covariate_2 + covariate_3

factor_a_t2 ~ factor_a_t1 + factor_b_t1 + factor_c_t1
factor_b_t2 ~ factor_a_t1 + factor_b_t1 + factor_c_t1
factor_c_t2 ~ factor_a_t1 + factor_b_t1 + factor_c_t1

outcome ~ factor_a_t2 + factor_b_t2 + factor_c_t2 + covariate_1 + covariate_2 + covariate_3'

**Comment by TDJorgensen** [comment] 2019-05-23 16:47
> Sample size is ~8,000. Only 3 exogenous covariates but model includes 6 factors all with ordinal indicators (4 levels)

Looks like you have 40 indicators with 3 thresholds each, so that's "only" 120 thresholds.  I wouldn't expect *N* = 8000 to be insufficient data.

> (i) run the model separately on each imputed dataset (using fixed.x = TRUE and conditional.x = TRUE),
> (ii) use parameterEstimates to extract standardised coefficients for each imputation,,
> (iii) use an external function (e.g. "mi.meld" from Amelia) to pool the estimates?

That would work!  The average of standardized coefficients is not equal to the standardized pooled coefficients, but it should be a damn close approximation.

**Comment by timcadman** [comment] 2019-06-04 08:36
Great - thanks for your help!

**Comment by TDJorgensen** [comment] 2019-06-07 15:06
OK, David and Tim (and anyone else keeping watch on this issue), the long wait is over.  The latest development versions of `lavaan` and `semTools` now make it possible to obtain standardized estimates from the `summary()` output even when `fixed.x=TRUE` or `conditional.x=TRUE`.  (All the other issues are also resolved with the `fitted`, `residuals`, and `fitMeasures` methods.)

```
install.packages("lavaan", repos = "http://www.da.ugent.be", type = "source")
devtools::install_github("simsem/semTools/semTools")
```

A current issue is that `lavaan`'s `print()` method excludes the `std.nox` column, if that is something you are interested in.  But that will be resolved before going to CRAN, and you can still see it by calling `summary(fit, standardized = TRUE, add.attributes = FALSE)`.

**Closed by TDJorgensen** 2019-06-07 15:06 UTC

**Comment by timcadman** [comment] 2019-06-07 15:09
I had just noticed this was working!! This is great - thanks again. Your support for this package is phenomenal.

best,

Tim

**Comment by TDJorgensen** [comment] 2019-06-07 15:44
You're welcome.  Small update: Turns out the omission of the `std.nox` column was intentional, to save space when `std.all` is already present.  To see `std.nox` (only) for `lavaan.mi` objects, you can just specifically request `summary(fit, standardized = "std.nox")`.
